PRO ZE_CMFGEN_READ_OBS_2D_V2,filename,modeldir,lambdavac,flux,num_rec
C=299792458.
;Revised version of ZE_CMFGEN_READ_OBS in order to read  OBSFRAME1, OBSFRAME2, OBSFRAME3 generated by 2D models.
;assuming MODEL is present in modeldir
spawn,'grep "Number of observer" '+modeldir+'MODEL',result,/sh
pos=strpos(result,':')
num_rec=string(strmid(result,pos+1))
print,modeldir+filename
OPENR, lun, modeldir+filename, /GET_LUN

header=strarr(4) 
READF,lun,header

obs_freq=dblarr(num_rec)
READF,lun,obs_freq

lambdavac=C/obs_freq*1E-05 ;vacuum lambda in Angstroms

header2=strarr(4) 
READF,lun,header2

flux=dblarr(num_rec)
READF,lun,flux

;Release the logical unit number and close the fortran file.  
FREE_LUN, lun  

END