;PRO ZE_WORK_SN_SPECTRA_DENSE_CSM_98S_WITH_SHIVVERS_visit_takashi

;ZE_READ_SPECTRA_COL_VEC,'/Users/jgroh/papers_in_preparation_groh/98s_shivvers/sn1998s-both.fluxnorm.drdzdr.flm',lobs,fobs ;redenning corrected shivvers
ZE_READ_SPECTRA_COL_VEC,'/Users/jgroh/papers_in_preparation_groh/98s_shivvers/sn1998s-both.fluxnorm2',lobs,fobs ;not corrected for redenning
ZE_READ_SPECTRA_COL_VEC,'/Users/jgroh/papers_in_preparation_groh/98s_shivvers/sn1998s-both.absfluxnorm.flm',lobs,fobs ;not corrected for redenning 

;ZE_CMFGEN_CREATE_OBSNORM,'/Users/jgroh/ze_models/grid_P060z14S0/model6250_T56420_L897212_logg_2d913_tauref20/obs/obs_fin_10','/Users/jgroh/ze_models/grid_P060z14S0/model6250_T56420_L897212_logg_2d913_tauref20/obscont/obs_cont',l01,f01,lmin=1150,lmax=10000
;ZE_CMFGEN_READ_OBS,'/Users/jgroh/ze_models/98s/14/obs20/obs_fin',l1,f1,/FLAM,lmin=3050,lmax=11000,/AIR
ZE_CMFGEN_READ_OBS,'/Users/jgroh/ze_models/98s/5/obs/obs_fin',l1,f1,/FLAM,lmin=3050,lmax=11000,/AIR
;ZE_CMFGEN_READ_OBS,'/Users/jgroh/ze_models/98s/37/OBSFLUX',l1,f1,/FLAM,lmin=1150,lmax=9000
;ZE_CMFGEN_READ_OBS,'/Users/jgroh/ze_models/etacar/mod16_groh/obs/obs_fin',l2,f2,/FLAM,lmin=1150,lmax=9000
ZE_CMFGEN_CREATE_OBSNORM,'/Users/jgroh/ze_models/98s/29/obs/obs_fin','/Users/jgroh/ze_models/98s/29/obscont/obs_fin',l29,f29n,lmin=3150,lmax=10000,/AIR
;ZE_CMFGEN_READ_OBS,'/Users/jgroh/ze_models/grid_P060z14S0/model6250_T56420_L897212_logg_2d913_tauref20/obs/obs_fin_10',l2,f2,/FLAM
;ZE_CMFGEN_READ_OBS,'/Users/jgroh/ze_models/SN_progenitor_grid/P040z14S0new_model106339_T048183_L0482467_logg3.576/obs/obs_fin',l2,f2,/FLAM
ZE_CMFGEN_READ_OBS,'/Users/jgroh/ze_models/98s/35/obs/obs_fin',l2,f2,/FLAM,lmin=3050,lmax=9000,/AIR
;ZE_CMFGEN_READ_OBSFLUX,'/Users/jgroh/ze_models/98s/38/OBSFLUX',l2,f2,/FLAM,lmin=1150,lmax=9000
;ZE_CMFGEN_READ_OBS,'/Users/jgroh/ze_models/13ast/47/obs/obs_fin',l2,f2,/FLAM,lmin=1150,lmax=11000
ZE_CMFGEN_READ_OBS,'/Users/jgroh/ze_models/98s/26/obs/obs_fin',l3,f3,/FLAM,lmin=3150,lmax=9000
ZE_CMFGEN_READ_OBS,'/Users/jgroh/ze_models/13ast/day6_1/OBSFLUX',l4,f4,/FLAM,lmin=3050,lmax=50000
ZE_CMFGEN_READ_OBS,'/Users/jgroh/ze_models/13ast/31/obs2/obs_fin',l5,f5,/FLAM,lmin=3150,lmax=11000

ZE_CMFGEN_READ_OBS,'/Users/jgroh/ze_models/prog13ast/2/obs/obs_fin',lprog,fprog,/FLAM,lmin=1150,lmax=9000

;ZE_CMFGEN_READ_OBSFLUX,'/Users/jgroh/ze_models/grid_P060z14S0/model6250_T56420_L897212_logg_2d913_tauref20/obs/obs_fin_10',l2,f2,/FLAM
STOP

;line_norm,lobs,fobs,fobsnorm,fobsnval,fobsxnodesnorm,fobsynodesnorm
;save,lobs,fobs,fobsnorm,fobsnval,fobsxnodesnorm,fobsynodesnorm,filename='/Users/jgroh/temp/98s_norm.sav'
;STOP
restore,'/Users/jgroh/temp/98s_norm.sav',/VERBOSE

;redshift correction of observed spectrum
z = 0.00283 ;original 
z = 0.00286
lambda_factor=1+z
lobs=lobs/lambda_Factor
;fobss=ZE_SHIFT_SPECTRA_VEL(lobs,fobs,846.9)
;fobs=fobss  

;convolving to the same resolution and regridding
f1cnvl=ZE_SPEC_CNVL_VEL(l1,f1,15.0)
f2cnvl=ZE_SPEC_CNVL_VEL(l2,f2,15.0)
linterp,l1,f1cnvl,lobs,f1cnvli
linterp,l2,f2cnvl,lobs,f2cnvli

f3cnvl=ZE_SPEC_CNVL_VEL(l3,f3,15.0)
linterp,l3,f3cnvl,lobs,f3cnvli

f4cnvl=ZE_SPEC_CNVL_VEL(l4,f4,15.0)
linterp,l4,f4cnvl,lobs,f4cnvli

f5cnvl=ZE_SPEC_CNVL_VEL(l5,f5,15.0)
linterp,l5,f5cnvl,lobs,f5cnvli

dist = lumdist(z) * 1e3
print,dist
dist=18.49e3 ;in kpc
dist=17.8e3

fm_unred, lobs,fobs, 0.05, fobsder,R_V=3.1
fobs=fobsder

;lineplot,lobs,fobsnorm
;lineplot,l1,f1cnvli

lplanck=findgen(10000)*10
bbflux=planck(lplanck,20000.)
bbflux=bbflux*1.2734d-21
lineplot,lobs,fobs*1e-15,title='obs' ;* 1e-15
;;lineplot,lobs,f2cnvli/(dist^2) *1.0
lineplot,l1,f1cnvl/dist^2 * 0.587088,title='3'  ;*0.63795
lineplot,l2,f2cnvl/(dist^2),title='4' ;*0.63795
;lineplot,l3,f3cnvl/(dist^2),title='5 ' ;*0.63795
;lineplot,l4,f4cnvl/(dist^2),title='25' ;*0.63795
;lineplot,l5,f5cnvl/(dist^2),title='31' ;*0.63795
;lineplot,lplanck,bbflux
;ZE_CMFGEN_EVOL_FIND_CLOSEST_MODEL,50000.,5e6,1e-2,400.,0.2,0.78,0.00002,2e-3,2e-4,xn_array_sort,tstar_array_sort,lstar_array_sort,mdot_array_sort,vinf_array_sort,r_t_array_sort,tcut=0.3,modelid='13ast1',xwidget=1
;ZE_WRITE_SPECTRA_COL_VEC,'/Users/jgroh/temp/13ast_model14_fwhm175_to_avishay_carbon_times0d1.dat',l2,f2cnvl/(dist^2) *0.63795
;compute R band magnitude
ZE_CMFGEN_EVOL_COMPUTE_MAGNITUDES_V2,'/Users/jgroh/ze_models/13ast/','23','ptf_r',Mstart,Lstart,tstart,absolute_magt,Mbolt,BCt,dist=108e3
ZE_CMFGEN_EVOL_COMPUTE_MAGNITUDES_V2,'/Users/jgroh/ze_models/13ast/','24','ptf_r',Mstart,Lstart,tstart,absolute_magt,Mbolt,BCt,dist=108e3


!P.Background = fsc_color('white')

;defines ewdata for reading, as generated by CMF_FLUX (including header)
ewdata='/Users/jgroh/ze_models/SN_progenitor_grid/P020z14S4_model049869_T020358_L0191044_logg2.200/obscont/ewdata_fin_ed'  


i=FILE_LINES(ewdata)
;declare arrays
lambdac=dblarr(i) & cont=lambdac & ew=lambdac & sob=strarr(i) & sobc=strarr(i)
lambdac1=0. & cont1=0. & ew1=0. & sob1='A2' 

;read lambda central, continuum intensity, EW and transition ID
ewdata_header=''
openu,1,ewdata
readf,1,ewdata_header
for k=0., i-2. do begin
readf,1,lambdac1,cont1,ew1,sob1
sob1=strsub(sob1,4,50)
lambdac[k]=lambdac1 & cont[k]=cont1 & ew[k]=ew1 & sob[k]=sob1
endfor
close,1

;full spec
ZE_CMFGEN_PLOT_SPECTRA_GENERAL_STACKED_EPS_FOR_2013CU_SN_PROGENITOR_PAPER,lobs,fobs*1e-15,'', TEXTOIDL('Flux (erg/s/cm^2/Angstrom)'),xrange=[3700,7500],yrange=[2e-15,2e-13],filename='98s_18_full',$
                                                                          x2=l1,y2=0.95*f1cnvl/(dist^2);,id_lambda=lambdac,id_text=sob,id_ew=ew

;
ZE_CMFGEN_PLOT_SPECTRA_GENERAL_STACKED_EPS_FOR_2013CU_SN_PROGENITOR_PAPER,lobs,fobs*1e-15,'', TEXTOIDL('Flux (erg/s/cm^2/Angstrom)'),xrange=[3878,4158],yrange=[1.6e-14,1.5e-13],filename='98s_18_38',$
                                                                          x2=l1,y2=0.90*f1cnvl/(dist^2);,id_lambda=lambdac,id_text=sob,id_ew=ew

;
ZE_CMFGEN_PLOT_SPECTRA_GENERAL_STACKED_EPS_FOR_2013CU_SN_PROGENITOR_PAPER,lobs,fobs*1e-15,'', TEXTOIDL('Flux (erg/s/cm^2/Angstrom)'),xrange=[4158,4400],yrange=[1.6e-14,1.5e-13],filename='98s_18_41',$
                                                                          x2=l1,y2=0.95*f1cnvl/(dist^2);,id_lambda=lambdac,id_text=sob,id_ew=ew

;
ZE_CMFGEN_PLOT_SPECTRA_GENERAL_STACKED_EPS_FOR_2013CU_SN_PROGENITOR_PAPER,lobs,fobs*1e-15,'', TEXTOIDL('Flux (erg/s/cm^2/Angstrom)'),xrange=[4400,4786],yrange=[1.6e-14,1.2e-13],filename='98s_18_44',$
                                                                          x2=l1,y2=0.95*f1cnvl/(dist^2);,id_lambda=lambdac,id_text=sob,id_ew=ew
;
ZE_CMFGEN_PLOT_SPECTRA_GENERAL_STACKED_EPS_FOR_2013CU_SN_PROGENITOR_PAPER,lobs,fobs*1e-15,'', TEXTOIDL('Flux (erg/s/cm^2/Angstrom)'),xrange=[4786,5200],yrange=[1.6e-14,1.69e-13],filename='98s_18_47',$
                                                                          x2=l1,y2=0.95*f1cnvl/(dist^2);,id_lambda=lambdac,id_text=sob,id_ew=ew

;
ZE_CMFGEN_PLOT_SPECTRA_GENERAL_STACKED_EPS_FOR_2013CU_SN_PROGENITOR_PAPER,lobs,fobs*1e-15,'', TEXTOIDL('Flux (erg/s/cm^2/Angstrom)'),xrange=[5200,5800],yrange=[1.6e-14,7e-14],filename='98s_18_52',$
                                                                          x2=l1,y2=0.92*f1cnvl/(dist^2);,id_lambda=lambdac,id_text=sob,id_ew=ew

;
ZE_CMFGEN_PLOT_SPECTRA_GENERAL_STACKED_EPS_FOR_2013CU_SN_PROGENITOR_PAPER,lobs,fobs*1e-15,'', TEXTOIDL('Flux (erg/s/cm^2/Angstrom)'),xrange=[5800,6000],yrange=[7e-15,5e-14],filename='98s_18_58',$
                                                                          x2=l1,y2=0.90*f1cnvl/(dist^2);,id_lambda=lambdac,id_text=sob,id_ew=ew

;
ZE_CMFGEN_PLOT_SPECTRA_GENERAL_STACKED_EPS_FOR_2013CU_SN_PROGENITOR_PAPER,lobs,fobs*1e-15,'', TEXTOIDL('Flux (erg/s/cm^2/Angstrom)'),xrange=[6400,6786],yrange=[7e-15,1.89e-13],filename='98s_18_65',$
                                                                          x2=l1,y2=0.92*f1cnvl/(dist^2);,id_lambda=lambdac,id_text=sob,id_ew=ew
;
ZE_CMFGEN_PLOT_SPECTRA_GENERAL_STACKED_EPS_FOR_2013CU_SN_PROGENITOR_PAPER,lobs,fobs*1e-15,'', TEXTOIDL('Flux (erg/s/cm^2/Angstrom)'),xrange=[6786,7300],yrange=[7e-15,3e-14],filename='98s_18_67',$
                                                                          x2=l1,y2=0.98*f1cnvl/(dist^2);,id_lambda=lambdac,id_text=sob,id_ew=ew

;progenitor magnitude in ptf-r
ZE_CMFGEN_EVOL_COMPUTE_MAGNITUDES_V2,'/Users/jgroh/ze_models/13ast/','46','ptf_r',Mstart,Lstart,tstart,absolute_magt,Mbolt,BCt,dist=108e3


rvtj='/Users/jgroh/ze_models/98s/27/RVTJ'
ZE_READ_RVTJ,rvtj,r,v,sigma,ed,t,chiross,fluxross,atom,ionden,den,clump,ND,NC,NP,NCF,mdot,lstar,output_format_date,$
    completion_of_model,program_date,was_t_fixed,species_name_con,greyt,heating_rad_decay

ZE_CMFGEN_COMPUTE_OPTICAL_DEPTH_TORSCL,CHIross,R,tauross

data2=read_ascii('/Users/jgroh/ze_models/98s/27/MEANOPAC',DATA_START=1,COMMENT_SYMBOL='NB')
taues=REFORM(data2.field01[10,*]*1D0)


;computes distance of shock front    
r_shock=ZE_COMPUTE_DISTANCE_SN_SHOCK_FRONT(15.5,1e4) ;15.5h, 1e4 km/s
r_light=ZE_COMPUTE_DISTANCE_SN_SHOCK_FRONT(15.5,2.9929e8) ;distance travelled by light in 15.5h
rectime=ZE_COMPUTE_RECOMBINATION_TIMESCALE(ed)
vwind=400.0  
;print,mdot*6.30321217d25/(4.*3.141592*((r_shock)^2)*vwind*1d5)

rstar=r[ND-1]
heff=0.007 *rstar;in units of rstar
den0=1e-9
;den1=den0*(exp(r0/r) -1 )/max(exp(r0/r) -1)
den1=den0*exp((Rstar - r)/heff)
den2=mdot*6.30321217d25/(4.*3.141592*((r*1d10)^2)*vwind*1d5)
transradius=min(where(den1-den2 GT 0))
dencomb=[den2[0:transradius-1],den1[transradius:nd-1]]


;plot v,den,line forming regions
data=read_ascii('/Users/jgroh/ze_models/98s/27/98s_27_lineform.dat',DATA_START=2)
v=replicate(40.,nd)
ZE_EVOL_PLOT_XY_GENERAL_EPS_V2,r*1e10,data.field01[1,*],TEXTOIDL('r (cm)'),TEXTOIDL('Line forming region'),'',linestyle1=0,color1='black',$ ;H0
                                _EXTRA=extra,/xlog,ylog=0,/nodata,xrange=[5.5e14,6.5e17],yrange=[-1,3],psxsize=900,psysize=400,filename='lineform_27',$
                                 x2=r*1e10,y2=data.field01[1,*],color2='red',linestyle2=0,double_yaxis=0,$;H+  
                                 x3=r*1e10,y3=data.field01[3,*],color3='blue',linestyle3=3,$ ;He +
                                 x4=r*1e10,y4=data.field01[5,*],color4='brown',linestyle4=2,$ ;He ++
                                 x5=r*1e10,y5=data.field01[7,*],color5='green',linestyle5=0,$ ;N3+  
                                 x6=r*1e10,y6=data.field01[9,*],color6='orange',linestyle6=5,$ ;N4+
                                 x7=r*1e10,y7=data.field01[11,*],color7='purple',linestyle7=2,$ ;N5+   
                                 x8=r*1e10,y8=taues,linestyle8=0,$ ;C3+  
;                                x9=data.field01[0,*],y9=data.field01[33,*],color9=colorcarb,linestyle9=1,$ ;C4+
;                                x10=data.field01[0,*],y10=data.field01[39,*],color_10=coloriron,linestyle_10=0,$ ;Fe5+    
;                                x11=data.field01[0,*],y11=data.field01[41,*],color_11=coloriron,linestyle_11=1,$ ;Fe6+      
;                                x12=data.field01[0,*],y12=data.field01[43,*],color_12=coloriron,linestyle_12=2,$ ;Fe7+                                                                                         
                                xcharsize=1.9,ycharsize=1.9,POSITION=[0.10,0.16,0.90,0.97],pthick=10,charthick=8,xthick=8,ythick=8;,/DOUBLE_YAXIS;,$
                                ;,/noyaxisvalues

;normalized line profiles to probe electron scattering wings
;lineplot,ZE_LAMBDA_TO_VEL(l29,6562.79), (f29n -1.0)/11.46, title='Halpha'
;lineplot,ZE_LAMBDA_TO_VEL(l29,4861.32), (f29n -1.0)/2.776, title='Hbeta'
;lineplot,ZE_LAMBDA_TO_VEL(l29,4340.6), (f29n -1.0)/1.120, title='Hgamma'
;lineplot,ZE_LAMBDA_TO_VEL(l29,4685.7), (f29n -1.0)/0.574, title='He II 4686'
;lineplot,ZE_LAMBDA_TO_VEL(l29,5875.66), (f29n -1.0)/1.496, title='He I 5786'

ZE_EVOL_PLOT_XY_GENERAL_EPS_V2,ZE_LAMBDA_TO_VEL(l29,6562.79), (f29n -1.0)/11.46,TEXTOIDL('v (km/s)'),TEXTOIDL('Flux normalized to peak'),'',linestyle1=0,color1='red',$ ;H0
                                _EXTRA=extra,xlog=0,ylog=0,xrange=[-2000,2000],yrange=[-0.08,1.01],psxsize=900,psysize=400,filename='line_norm_es_27',$
                                 x2=ZE_LAMBDA_TO_VEL(l29,4861.32), y2=(f29n -1.0)/2.776,color2='blue',linestyle2=0,double_yaxis=0,$;H+  
                                 x3=ZE_LAMBDA_TO_VEL(l29,4340.6), y3=(f29n -1.0)/1.120,color3='brown',linestyle3=3,$ ;He +
                                 x4=ZE_LAMBDA_TO_VEL(l29,4685.7), y4=(f29n -1.0)/0.574,color4='green',linestyle4=2,$ ;He ++
                                 x5=ZE_LAMBDA_TO_VEL(l29,5875.66), y5=(f29n -1.0)/1.496,color5='orange',linestyle5=0,$ ;N3+  
;                                x9=data.field01[0,*],y9=data.field01[33,*],color9=colorcarb,linestyle9=1,$ ;C4+
;                                x10=data.field01[0,*],y10=data.field01[39,*],color_10=coloriron,linestyle_10=0,$ ;Fe5+    
;                                x11=data.field01[0,*],y11=data.field01[41,*],color_11=coloriron,linestyle_11=1,$ ;Fe6+      
;                                x12=data.field01[0,*],y12=data.field01[43,*],color_12=coloriron,linestyle_12=2,$ ;Fe7+                                                                                         
                                xcharsize=1.9,ycharsize=1.9,POSITION=[0.10,0.16,0.90,0.97],pthick=10,charthick=8,xthick=8,ythick=8;,/DOUBLE_YAXIS;,$
                                ;,/noyaxisvalues                             

ZE_WRITE_SPECTRA_COL_VEC,'/Users/jgroh/temp/98s_27_lambda_flux.dat',l2,f2cnvl/(dist^2)*1.09024
;                                
;writecol,'/Users/jgroh/temp/98s_27_tau_den.dat',r*1e10,v,alog10(tauross),t
;
;writecol,'/Users/jgroh/temp/98s_27_lineform_es.dat',r*1e10,REFORM(data.field01[1,*]),REFORM(data.field01[3,*]),REFORM(data.field01[5,*]),REFORM(data.field01[7,*]),REFORM(data.field01[9,*]),REFORM(data.field01[11,*]),taues
;
;writecol,'/Users/jgroh/temp/98s_27_lineprofiles_norm_to_peak.dat',ZE_LAMBDA_TO_VEL(l29,6562.79), (f29n -1.0)/11.46, ZE_LAMBDA_TO_VEL(l29,4861.32), (f29n -1.0)/2.776,$
;                                                                  ZE_LAMBDA_TO_VEL(l29,4340.6), (f29n -1.0)/1.120,ZE_LAMBDA_TO_VEL(l29,4685.7), (f29n -1.0)/0.574,$
;                                                                  ZE_LAMBDA_TO_VEL(l29,5875.66), (f29n -1.0)/1.496
;
;;read if_struct.dat file with ionization structure, generated with dispgen if_* option
;order of ions: H, He, N, O, C, Fe
;ionization stages:
;
; Curve  1 is due to: HI
; Curve  2 is due to: H2
;
; Curve  1 is due to: HeI
; Curve  2 is due to: He2
; Curve  3 is due to: HeIII
;
;
; Curve  1 is due to: NIII
; Curve  2 is due to: NIV
; Curve  3 is due to: NV
; Curve  4 is due to: NSIX
;
; Curve  1 is due to: OIII
; Curve  2 is due to: OIV
; Curve  3 is due to: OV
; Curve  4 is due to: OSIX
; Curve  5 is due to: OSEV
;
;
; Curve  1 is due to: CIII
; Curve  2 is due to: CIV
; Curve  3 is due to: CV
; 
; Curve  1 is due to: FeIV
; Curve  2 is due to: FeV
; Curve  3 is due to: FeSIX
; Curve  4 is due to: FeSEV
; Curve  5 is due to: FeVIII

data=read_ascii('/Users/jgroh/ze_models/98s/18/98s_18_ionstruct.dat',DATA_START=0)
;convert r to cm
data.field01[0,*]=10^(data.field01[0,*])*1.5e14
colorhyd='black'
colorhe='blue'
colornit='green'
colorcarb='red'
coloroxy='cyan'
coloriron='orange'
ZE_EVOL_PLOT_XY_GENERAL_EPS_V2,data.field01[0,*],data.field01[1,*],TEXTOIDL(''),'relative ionization mass fraction','',linestyle1=0,color1=colorhyd,$ ;H0
                                _EXTRA=extra,/xlog,xrange=[1.3e14,1.5e17],yrange=[-9,0.3],psxsize=900,psysize=400,filename='ionstruct_46_post',xtickformat='(A3)',$
                                x2=data.field01[0,*],y2=data.field01[3,*],color2=colorhyd,linestyle2=1,$;H+  
                                x3=data.field01[0,*],y3=data.field01[7,*],color3=colorhe,linestyle3=0,$ ;He +
                                x4=data.field01[0,*],y4=data.field01[9,*],color4=colorhe,linestyle4=1,$ ;He ++
                                x5=data.field01[0,*],y5=data.field01[13,*],color5=colornit,linestyle5=0,$ ;N3+  
                                x6=data.field01[0,*],y6=data.field01[15,*],color6=colornit,linestyle6=1,$ ;N4+
                                x7=data.field01[0,*],y7=data.field01[17,*],color7=colornit,linestyle7=2,$ ;N5+   
                                x8=data.field01[0,*],y8=data.field01[31,*],color8=colorcarb,linestyle8=0,$ ;C3+  
                                x9=data.field01[0,*],y9=data.field01[33,*],color9=colorcarb,linestyle9=1,$ ;C4+
                                x10=data.field01[0,*],y10=data.field01[39,*],color_10=coloriron,linestyle_10=0,$ ;Fe5+    
                                x11=data.field01[0,*],y11=data.field01[41,*],color_11=coloriron,linestyle_11=1,$ ;Fe6+      
                                x12=data.field01[0,*],y12=data.field01[43,*],color_12=coloriron,linestyle_12=2,$ ;Fe7+                                                                                         
                                xcharsize=1.9,ycharsize=1.9,POSITION=[0.10,0.16,0.90,0.97],pthick=10,charthick=8,xthick=8,ythick=8;,/DOUBLE_YAXIS;,$
                                ;,/noyaxisvalues


END